
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common

bpetsc_impl.o: bpetsc_impl.c bpetsc_impl.h bsubspace_impl.h shell_context.h bpetsc_template_1.h bpetsc_template_1.c bpetsc_template_2.h bpetsc_template_2.c

bcuda_impl.o: bcuda_impl.cu bcuda_impl.h bsubspace_impl.h shell_context.h bcuda_template.h bcuda_template_private.h bcuda_template.cu
