FROM python:3.9-bullseye AS build
LABEL org.opencontainers.image.authors="Greg Meyer <gregory.meyer@gmail.com>"

# install dependencies
# TODO: it would be great to install scalapack here as well, it doesn't seem to work though :-(
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gfortran \
    mpi-default-dev \
    libopenblas-dev \
    libmumps-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# copy petsc config files
RUN mkdir /opt/dynamite
WORKDIR /opt/dynamite
COPY petsc_config petsc_config

ARG PETSC_ARCH=complex-opt
ENV PETSC_ARCH=$PETSC_ARCH

# install PETSc
ARG PETSC_VERSION=3.16.1
WORKDIR /opt
RUN curl https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-$PETSC_VERSION.tar.gz | tar xzf -
WORKDIR /opt/petsc-$PETSC_VERSION
ENV PETSC_DIR=/opt/petsc-$PETSC_VERSION

RUN cp ../dynamite/petsc_config/$PETSC_ARCH.py . && \
    ./$PETSC_ARCH.py --download-scalapack=1 --with-mumps=1 && \
    make all

# install SLEPc
ARG SLEPC_VERSION=3.16.1
WORKDIR /opt
RUN curl https://slepc.upv.es/download/distrib/slepc-$SLEPC_VERSION.tar.gz | tar xzf -
WORKDIR /opt/slepc-$SLEPC_VERSION
ENV SLEPC_DIR=/opt/slepc-$SLEPC_VERSION
RUN ./configure && make

# install python packages
# they need to be installed in order, so we can't do pip install -r requirements.txt....
WORKDIR /opt/dynamite

RUN pip3 install --no-cache-dir --upgrade pip

COPY requirements.txt requirements.txt
RUN while read PACKAGE; \
        do pip3 install --no-cache-dir --no-warn-script-location $PACKAGE; \
    done <requirements.txt

# mpi4py is useful and required for the tests
RUN pip3 install --no-cache-dir --no-warn-script-location mpi4py==3.0.3

# install dynamite!
ARG GIT_BRANCH=unknown
ARG GIT_COMMIT=unknown

RUN echo $GIT_BRANCH > /opt/dynamite/dnm_branch && \
    echo $GIT_COMMIT > /opt/dynamite/dnm_commit

COPY . .
ENV DNM_DOCKER=1
RUN pip3 install ./


FROM python:3.9-slim-bullseye as release

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    mpi-default-bin \
    libopenblas0 \
    libmumps-5.3 \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ARG PETSC_ARCH=complex-opt
ARG PETSC_VERSION=3.16.1
ARG SLEPC_VERSION=3.16.1

# get petsc and slepc libraries
COPY --from=build /opt/petsc-$PETSC_VERSION/$PETSC_ARCH/lib /opt/petsc-$PETSC_VERSION/$PETSC_ARCH/lib
COPY --from=build /opt/slepc-$SLEPC_VERSION/$PETSC_ARCH/lib /opt/slepc-$SLEPC_VERSION/$PETSC_ARCH/lib

# get all the python stuff
COPY --from=build /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/

# switch to non-privileged user
RUN groupadd dnm && useradd --no-log-init -m -g dnm dnm
USER dnm

# include benchmarking and examples
COPY benchmarking /home/dnm/benchmarking
COPY examples /home/dnm/examples

# so that we can tell we are in a container
ENV DNM_DOCKER=1

# make work directory for mounting local files
VOLUME /home/dnm/work
WORKDIR /home/dnm


FROM release AS jupyter

# install jupyter
USER root
RUN pip3 install --no-cache-dir jupyterlab

# run it!
USER dnm
WORKDIR /home/dnm
EXPOSE 8888
CMD ["jupyter", "lab", "--no-browser", "--ip=0.0.0.0"]
